---
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes
<<<<<<< HEAD:roles/ceph-common/handlers/main.yml
=======

- name: disable ntpd
  failed_when: false
  service:
    name: ntpd
    state: stopped
    enabled: no

- name: disable chronyd
  failed_when: false
  service:
    name: chronyd
    enabled: no
    state: stopped

- name: disable timesyncd
  failed_when: false
  service:
    name: timesyncd
    enabled: no
    state: stopped
>>>>>>> 6fa757d3... ceph-infra: disable unrequired NTP services:roles/ceph-infra/handlers/main.yml
